"""empty message

Revision ID: 4a3cbd33f796
Revises: 9e05a7b8db68
Create Date: 2025-01-22 18:47:26.787154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a3cbd33f796'
down_revision = '9e05a7b8db68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('climate', sa.String(length=80), nullable=True),
    sa.Column('diameter', sa.Integer(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('terrain', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('character')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('birth_year', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('height', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=True),
    sa.Column('skin_color', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('eye_color', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='character_pkey')
    )
    op.drop_table('planets')
    # ### end Alembic commands ###
